# Generated by Django 3.1.4 on 2021-09-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocMaster',
            fields=[
                ('DocumentCode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('DocementName', models.CharField(max_length=250)),
                ('ExpDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DocDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Revision', models.CharField(max_length=25)),
                ('RevDate', models.DateField()),
                ('RevCause', models.CharField(max_length=500)),
                ('DocumentCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docapp.docmaster')),
            ],
        ),
    ]
