# Generated by Django 3.1.4 on 2021-09-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docmaster',
            old_name='DocementName',
            new_name='DocumentName',
        ),
    ]
